"""empty message

Revision ID: d23b06203729
Revises: 
Create Date: 2025-10-31 07:35:15.823998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23b06203729'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('date_reg', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('category',
    sa.Column('cat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cat_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('product',
    sa.Column('prod_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prod_name', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('dateadded', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('prod_id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_prod_name'), ['prod_name'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.String(length=100), nullable=False),
    sa.Column('lname', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('user_dp', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('pwd', sa.String(length=255), nullable=False),
    sa.Column('regdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_fname'), ['fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_lname'), ['lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('carts',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_prod_id', sa.Integer(), nullable=True),
    sa.Column('cart_user_id', sa.Integer(), nullable=True),
    sa.Column('cart_amt', sa.Integer(), nullable=True),
    sa.Column('cart_qty', sa.Integer(), nullable=True),
    sa.Column('cart_payable', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_prod_id'], ['product.prod_id'], ),
    sa.ForeignKeyConstraint(['cart_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('amt_payable', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prod_id'], ['product.prod_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('img_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.prod_id'], ),
    sa.PrimaryKeyConstraint('img_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_status', sa.Enum('1', '0', name='order_status'), nullable=True),
    sa.Column('order_userid', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('order_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_userid'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('orderdetails',
    sa.Column('details_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details_prod_id', sa.Integer(), nullable=True),
    sa.Column('details_orderid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['details_orderid'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['details_prod_id'], ['product.prod_id'], ),
    sa.PrimaryKeyConstraint('details_id')
    )
    op.create_table('payment',
    sa.Column('pay_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pay_user', sa.Integer(), nullable=True),
    sa.Column('pay_order', sa.Integer(), nullable=True),
    sa.Column('pay_amt', sa.Float(), nullable=True),
    sa.Column('pay_ref', sa.String(length=200), nullable=False),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('pay_status', sa.Enum('pending', 'paid', 'failed', name='pay_status'), nullable=True),
    sa.Column('pay_actual', sa.Float(), nullable=True),
    sa.Column('pay_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pay_order'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['pay_user'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pay_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('orderdetails')
    op.drop_table('orders')
    op.drop_table('images')
    op.drop_table('history')
    op.drop_table('carts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_lname'))
        batch_op.drop_index(batch_op.f('ix_users_fname'))

    op.drop_table('users')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_prod_name'))

    op.drop_table('product')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
