"""empty message

Revision ID: e5f52313a99b
Revises: d23b06203729
Create Date: 2025-11-12 12:53:59.029608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f52313a99b'
down_revision = 'd23b06203729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('cart_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cart_amt',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('cart_amt',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cart_qty',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
